Repository Lightning-AI/lightning-Habana, pull requests merged in 2023-06, with the labels that each got.

#41 Update docs and Hpu media work around
  CHANGELOG.md
  README.md
  src/lightning_habana/pytorch/datamodule/dataloaders/resnet_media_pipe.py
Labels: documentation

#43 fixing undirected imports
  src/lightning_habana/pytorch/datamodule/datamodule.py
  src/lightning_habana/pytorch/strategies/deepspeed.py
Labels: bug

#45 Add graph breaks with lazy mode in test/eval phase
  CHANGELOG.md
  examples/pytorch/mnist_sample.py
  src/lightning_habana/__about__.py
  src/lightning_habana/pytorch/strategies/parallel.py
  src/lightning_habana/pytorch/strategies/single.py
Labels: bug

#48 docs: prefer lai over pl
  docs/source/advanced.rst
  docs/source/conf.py
  docs/source/intermediate.rst
Labels: documentation

#47 ci: separate typing extra
  .github/workflows/ci-checks.yml
  _requirements/docs.txt
  _requirements/test.txt
  _requirements/typing.txt
Labels: enhancement

#44 Fix imports to support ecosystem CI
  CHANGELOG.md
  src/lightning_habana/pytorch/strategies/deepspeed.py
  src/lightning_habana/pytorch/strategies/parallel.py
  src/lightning_habana/pytorch/strategies/single.py
  tests/test_pytorch/test_accelerator.py
Labels: bug
