Repository Lightning-AI/lightning-Habana, pull requests merged in 2023-10, with the labels that each got.

#87 precommit: update
  .pre-commit-config.yaml
  pyproject.toml
  src/lightning_habana/fabric/accelerator.py
  src/lightning_habana/fabric/plugins/io_plugin.py
  src/lightning_habana/fabric/plugins/precision.py
  src/lightning_habana/pytorch/accelerator.py
  src/lightning_habana/pytorch/datamodule/dataloaders/resnet_media_pipe.py
  src/lightning_habana/pytorch/datamodule/datamodule.py
  src/lightning_habana/pytorch/plugins/io_plugin.py
  src/lightning_habana/pytorch/plugins/precision.py
  src/lightning_habana/pytorch/profiler/profiler.py
  src/lightning_habana/pytorch/strategies/deepspeed.py
  src/lightning_habana/utils/hpu_distributed.py
  src/lightning_habana/utils/resources.py
  tests/test_common/test_resources.py
  tests/test_fabric/test_hpu_accelerator.py
  tests/test_fabric/test_hpu_precision.py
  tests/test_fabric/test_hpu_strategy.py
  tests/test_pytorch/test_accelerator.py
  tests/test_pytorch/test_deepspeed.py
Labels: enhancement

#88 precommit: enable codespell
  .pre-commit-config.yaml
  docs/source/advanced.rst
  docs/source/intermediate.rst
  setup.py
  src/lightning_habana/utils/resources.py
  tests/__init__.py
  tests/test_pytorch/test_accelerator.py
  tests/test_pytorch/test_precision.py
Labels: enhancement

#92 notes how to upgrade HW
  .azure/README.md
Labels: documentation

#97 ci: bump base image to ubuntu 22.04
  .azure/hpu-tests.yml
Labels: enhancement

#96 ci/azure: drop `sudo` from workflow
  .azure/hpu-tests.yml
Labels: enhancement

#103 docker: drop buidling ci runner
  .github/workflows/ci-dockers.yml
  README.md
  dockers/ci-runner-hpu/Dockerfile
Labels: ci / tests

#104 ci: de-duplicate & validate pkg with extras
  .github/workflows/ci-checks.yml
Labels: enhancement, ci / tests

#101 automate version bump in lightning docs
  .github/workflows/release-pypi.yml
Labels: ci / tests

#106 Upgrade to Synapse AI Release 1.12.1
  .azure/hpu-tests.yml
  CHANGELOG.md
  README.md
  src/lightning_habana/__about__.py
  src/lightning_habana/pytorch/accelerator.py
  src/lightning_habana/pytorch/strategies/deepspeed.py
  src/lightning_habana/pytorch/strategies/parallel.py
  src/lightning_habana/pytorch/strategies/single.py
Labels: enhancement
